// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Cabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CounselorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CounselorId");

                    b.ToTable("Cabins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CounselorId = 1,
                            Name = "First"
                        },
                        new
                        {
                            Id = 2,
                            CounselorId = 2,
                            Name = "Second"
                        },
                        new
                        {
                            Id = 3,
                            CounselorId = 3,
                            Name = "Third"
                        },
                        new
                        {
                            Id = 4,
                            CounselorId = 4,
                            Name = "Fourth"
                        },
                        new
                        {
                            Id = 5,
                            CounselorId = 5,
                            Name = "Fifth"
                        });
                });

            modelBuilder.Entity("Domain.Camper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<int?>("CabinId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CabinId");

                    b.HasIndex("CabinId1");

                    b.ToTable("Campers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CabinId = 1,
                            DateOfBirth = new DateTime(2012, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6243),
                            Name = "Niklas",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 2,
                            CabinId = 1,
                            DateOfBirth = new DateTime(2011, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6498),
                            Name = "Maja",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 3,
                            CabinId = 1,
                            DateOfBirth = new DateTime(2010, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6507),
                            Name = "Lina",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 4,
                            CabinId = 1,
                            DateOfBirth = new DateTime(2012, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6510),
                            Name = "Paula",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 5,
                            CabinId = 2,
                            DateOfBirth = new DateTime(2013, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6514),
                            Name = "Anders",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 6,
                            CabinId = 2,
                            DateOfBirth = new DateTime(2014, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6519),
                            Name = "Ahmed",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 7,
                            CabinId = 2,
                            DateOfBirth = new DateTime(2013, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6522),
                            Name = "Erik",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 8,
                            CabinId = 2,
                            DateOfBirth = new DateTime(2012, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6525),
                            Name = "Frida",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 9,
                            CabinId = 3,
                            DateOfBirth = new DateTime(2011, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6528),
                            Name = "Paul",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 10,
                            CabinId = 3,
                            DateOfBirth = new DateTime(2011, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6532),
                            Name = "Mikael",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 11,
                            CabinId = 3,
                            DateOfBirth = new DateTime(2010, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6535),
                            Name = "John",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 12,
                            CabinId = 3,
                            DateOfBirth = new DateTime(2009, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6538),
                            Name = "Silvio",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 13,
                            CabinId = 4,
                            DateOfBirth = new DateTime(2011, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6541),
                            Name = "Per",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 14,
                            CabinId = 4,
                            DateOfBirth = new DateTime(2010, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6544),
                            Name = "Leo",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 15,
                            CabinId = 4,
                            DateOfBirth = new DateTime(2011, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6547),
                            Name = "Howard",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 16,
                            CabinId = 4,
                            DateOfBirth = new DateTime(2012, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6551),
                            Name = "Ross",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 17,
                            CabinId = 5,
                            DateOfBirth = new DateTime(2011, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6554),
                            Name = "Rachel",
                            PhoneNumber = "0711254895"
                        },
                        new
                        {
                            Id = 18,
                            CabinId = 5,
                            DateOfBirth = new DateTime(2013, 1, 15, 12, 31, 51, 250, DateTimeKind.Local).AddTicks(6558),
                            Name = "Jakob",
                            PhoneNumber = "0711254895"
                        });
                });

            modelBuilder.Entity("Domain.CamperRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CabinId");

                    b.HasIndex("CamperId")
                        .IsUnique();

                    b.ToTable("CamperRegistries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CabinId = 1,
                            CamperId = 1,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(3732),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(3965)
                        },
                        new
                        {
                            Id = 2,
                            CabinId = 1,
                            CamperId = 2,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4223),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4230)
                        },
                        new
                        {
                            Id = 3,
                            CabinId = 1,
                            CamperId = 3,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4235),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4238)
                        },
                        new
                        {
                            Id = 4,
                            CabinId = 1,
                            CamperId = 4,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4243),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4246)
                        },
                        new
                        {
                            Id = 5,
                            CabinId = 2,
                            CamperId = 5,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4251),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4253)
                        },
                        new
                        {
                            Id = 6,
                            CabinId = 2,
                            CamperId = 6,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4260),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4263)
                        },
                        new
                        {
                            Id = 7,
                            CabinId = 2,
                            CamperId = 7,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4267),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4270)
                        },
                        new
                        {
                            Id = 8,
                            CabinId = 2,
                            CamperId = 8,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4273),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4277)
                        },
                        new
                        {
                            Id = 9,
                            CabinId = 3,
                            CamperId = 9,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4280),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4283)
                        },
                        new
                        {
                            Id = 10,
                            CabinId = 3,
                            CamperId = 10,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4288),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4291)
                        },
                        new
                        {
                            Id = 11,
                            CabinId = 3,
                            CamperId = 11,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4294),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4297)
                        },
                        new
                        {
                            Id = 12,
                            CabinId = 3,
                            CamperId = 12,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4300),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4303)
                        },
                        new
                        {
                            Id = 13,
                            CabinId = 4,
                            CamperId = 13,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4307),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4309)
                        },
                        new
                        {
                            Id = 14,
                            CabinId = 4,
                            CamperId = 14,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4312),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4315)
                        },
                        new
                        {
                            Id = 15,
                            CabinId = 4,
                            CamperId = 15,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4320),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4321)
                        },
                        new
                        {
                            Id = 16,
                            CabinId = 4,
                            CamperId = 16,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4324),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4326)
                        },
                        new
                        {
                            Id = 17,
                            CabinId = 5,
                            CamperId = 17,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4328),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4330)
                        },
                        new
                        {
                            Id = 18,
                            CabinId = 5,
                            CamperId = 18,
                            CheckIn = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4334),
                            CheckOut = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(4335)
                        });
                });

            modelBuilder.Entity("Domain.Counselor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Counselors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Storgatan10",
                            DateOfBirth = new DateTime(1992, 1, 15, 12, 31, 51, 247, DateTimeKind.Local).AddTicks(6723),
                            Email = "counc1@th.com",
                            Name = "Anders Counselsson",
                            PhoneNumber = "0700545641"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Göteborgsvägen 2",
                            DateOfBirth = new DateTime(1999, 1, 15, 12, 31, 51, 249, DateTimeKind.Local).AddTicks(7526),
                            Email = "counc2@th.com",
                            Name = "Erik Test",
                            PhoneNumber = "0700274641"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Torggatan1",
                            DateOfBirth = new DateTime(1996, 1, 15, 12, 31, 51, 249, DateTimeKind.Local).AddTicks(7555),
                            Email = "counc3@th.com",
                            Name = "Johan Svart",
                            PhoneNumber = "0703545641"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Lillegatan4",
                            DateOfBirth = new DateTime(1993, 1, 15, 12, 31, 51, 249, DateTimeKind.Local).AddTicks(7560),
                            Email = "counc4@th.com",
                            Name = "Jimmie Svensson",
                            PhoneNumber = "0787445641"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kunggatan3",
                            DateOfBirth = new DateTime(1997, 1, 15, 12, 31, 51, 249, DateTimeKind.Local).AddTicks(7563),
                            Email = "counc5@th.com",
                            Name = "Maja Andersson",
                            PhoneNumber = "0700543421"
                        });
                });

            modelBuilder.Entity("Domain.CounselorRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AssignmentEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AssignmentStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<int>("CounselorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CabinId");

                    b.HasIndex("CounselorId")
                        .IsUnique();

                    b.ToTable("CounselorRegistries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignmentEnd = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8454),
                            AssignmentStart = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8226),
                            CabinId = 1,
                            CounselorId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignmentEnd = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8776),
                            AssignmentStart = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8770),
                            CabinId = 2,
                            CounselorId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignmentEnd = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8782),
                            AssignmentStart = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8780),
                            CabinId = 3,
                            CounselorId = 3
                        },
                        new
                        {
                            Id = 4,
                            AssignmentEnd = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8787),
                            AssignmentStart = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8785),
                            CabinId = 4,
                            CounselorId = 4
                        },
                        new
                        {
                            Id = 5,
                            AssignmentEnd = new DateTime(2022, 4, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8791),
                            AssignmentStart = new DateTime(2022, 1, 15, 12, 31, 51, 251, DateTimeKind.Local).AddTicks(8790),
                            CabinId = 5,
                            CounselorId = 5
                        });
                });

            modelBuilder.Entity("Domain.NextOfKin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CamperId");

                    b.ToTable("NextOfKins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Gata6",
                            CamperId = 1,
                            Email = "parent1@test.com",
                            Name = "Ken",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gata7",
                            CamperId = 2,
                            Email = "parent2@test.com",
                            Name = "Anders",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Gata8",
                            CamperId = 3,
                            Email = "parent3@test.com",
                            Name = "Lina",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Gata4",
                            CamperId = 4,
                            Email = "parent4@test.com",
                            Name = "Per",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Gata5",
                            CamperId = 5,
                            Email = "parent5@test.com",
                            Name = "Mikael",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Gata1",
                            CamperId = 6,
                            Email = "parent6@test.com",
                            Name = "Johnny",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Gata45",
                            CamperId = 7,
                            Email = "parent7@test.com",
                            Name = "Leonard",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Gata54",
                            CamperId = 8,
                            Email = "parent8@test.com",
                            Name = "Ross",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Gata42",
                            CamperId = 9,
                            Email = "parent9@test.com",
                            Name = "Chandler",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Gata64",
                            CamperId = 10,
                            Email = "parent10@test.com",
                            Name = "Gunther",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Gata61",
                            CamperId = 11,
                            Email = "parent11@test.com",
                            Name = "Joey",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Gata45",
                            CamperId = 12,
                            Email = "parent12@test.com",
                            Name = "Josef",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Gata25",
                            CamperId = 13,
                            Email = "parent13@test.com",
                            Name = "Stefan",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Gata48",
                            CamperId = 14,
                            Email = "parent14@test.com",
                            Name = "Fredrick",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Gata66",
                            CamperId = 15,
                            Email = "parent15@test.com",
                            Name = "Marco",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Gata69",
                            CamperId = 16,
                            Email = "parent16@test.com",
                            Name = "Polo",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Gata74",
                            CamperId = 17,
                            Email = "parent17@test.com",
                            Name = "Cameron",
                            PhoneNumber = "071254864"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Gata87",
                            CamperId = 18,
                            Email = "parent18@test.com",
                            Name = "Mitchel",
                            PhoneNumber = "071254864"
                        });
                });

            modelBuilder.Entity("Domain.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CamperId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CamperId = 1,
                            EndTime = new DateTime(2022, 1, 15, 14, 31, 51, 252, DateTimeKind.Local).AddTicks(1665),
                            StartTime = new DateTime(2022, 1, 15, 12, 31, 51, 252, DateTimeKind.Local).AddTicks(1472),
                            VisitorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CamperId = 2,
                            EndTime = new DateTime(2022, 1, 15, 13, 31, 51, 252, DateTimeKind.Local).AddTicks(2007),
                            StartTime = new DateTime(2022, 1, 15, 12, 31, 51, 252, DateTimeKind.Local).AddTicks(2001),
                            VisitorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CamperId = 3,
                            EndTime = new DateTime(2022, 1, 15, 15, 31, 51, 252, DateTimeKind.Local).AddTicks(2012),
                            StartTime = new DateTime(2022, 1, 15, 12, 31, 51, 252, DateTimeKind.Local).AddTicks(2010),
                            VisitorId = 3
                        });
                });

            modelBuilder.Entity("Domain.Cabin", b =>
                {
                    b.HasOne("Domain.Counselor", "Counselor")
                        .WithMany()
                        .HasForeignKey("CounselorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counselor");
                });

            modelBuilder.Entity("Domain.Camper", b =>
                {
                    b.HasOne("Domain.Cabin", "Cabin")
                        .WithMany()
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Cabin", null)
                        .WithMany("Campers")
                        .HasForeignKey("CabinId1");

                    b.Navigation("Cabin");
                });

            modelBuilder.Entity("Domain.CamperRegistry", b =>
                {
                    b.HasOne("Domain.Cabin", "Cabin")
                        .WithMany()
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Camper", "Camper")
                        .WithOne()
                        .HasForeignKey("Domain.CamperRegistry", "CamperId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cabin");

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("Domain.CounselorRegistry", b =>
                {
                    b.HasOne("Domain.Cabin", "Cabin")
                        .WithMany()
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Counselor", "Counselor")
                        .WithOne()
                        .HasForeignKey("Domain.CounselorRegistry", "CounselorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cabin");

                    b.Navigation("Counselor");
                });

            modelBuilder.Entity("Domain.NextOfKin", b =>
                {
                    b.HasOne("Domain.Camper", "Camper")
                        .WithMany("NextOfKins")
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("Domain.Visit", b =>
                {
                    b.HasOne("Domain.Camper", "Camper")
                        .WithMany()
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.NextOfKin", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Camper");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("Domain.Cabin", b =>
                {
                    b.Navigation("Campers");
                });

            modelBuilder.Entity("Domain.Camper", b =>
                {
                    b.Navigation("NextOfKins");
                });
#pragma warning restore 612, 618
        }
    }
}
